# example auto pull, check and reload zone
stages:
   - pull
   - validate
   - reload
   - notify

task1-pull:
  stage: pull
  script: cd /opt/gitlab/dns/ && /usr/bin/git pull
  tags:
    - dns

task2-validate-zubr-tech:
  stage: validate
  script: named-checkzone -k fail example.com /var/named/master/example.com.zone
  tags:
    - dns

task2-validate-10:
  stage: validate
  script: named-checkzone -k fail 10.in-addr.arpa /var/named/master/10.in-addr.arpa.zone
  tags:
    - dns

task3-reload:
  stage: reload
  script:
  - /usr/sbin/rndc reload
  - sh .ci-notify.sh "✅ - success"
  tags:
    - dns

notify_error:
  stage: notify
  script:
  - sh .ci-notify.sh "❌ - failed"
  when: on_failure #deploy fail
  tags:
    - dns